services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    image: skadssagar/ecommerce-app-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    image: skadssagar/ecommerce-app-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: always
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
        - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge



